steps:
  - name: node
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "SLACK_SIGNING_SECRET=${_SLACK_SIGNING_SECRET}"
      - "SLACK_BOT_TOKEN=${_SLACK_BOT_TOKEN}"
      - "SLACK_APP_TOKEN=${_SLACK_APP_TOKEN}"
      - "TWILIO_ACCOUNT_SID=${_TWILIO_ACCOUNT_SID}"
      - "TWILIO_AUTH_TOKEN=${_TWILIO_AUTH_TOKEN}"

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - gcr.io/$PROJECT_ID/fs-assistant-slackbot
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/fs-assistant-slackbot
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - app
      - deploy
      - deploy.yaml
      - "--image-url"
      - gcr.io/$PROJECT_ID/fs-assistant-slackbot:latest
    entrypoint: gcloud
images:
  - gcr.io/$PROJECT_ID/fs-assistant-slackbot
timeout: 1800s
